version: '3.8'
services:
  db:
    container_name: postgresql_db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: liftuser
      POSTGRES_PASSWORD: liftpwd
      POSTGRES_DB: lift_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lift@lift.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
